"""initial schema: 21 таблица DATABASE v1.0

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 19:25:55.794309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('max_user_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('can_start_trip', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('access_block_reason', sa.Text(), nullable=True),
    sa.Column('access_changed_by', sa.UUID(), nullable=True),
    sa.Column('max_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('bot_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("role IN ('employee', 'admin')", name=op.f('ck_employees_role')),
    sa.CheckConstraint('can_start_trip OR access_block_reason IS NOT NULL', name=op.f('ck_employees_block_reason')),
    sa.CheckConstraint('char_length(display_name) BETWEEN 1 AND 200', name=op.f('ck_employees_display_name_len')),
    sa.CheckConstraint('max_user_id > 0', name=op.f('ck_employees_max_user_id_positive')),
    sa.CheckConstraint('version > 0', name=op.f('ck_employees_version_positive')),
    sa.ForeignKeyConstraint(['access_changed_by'], ['employees.id'], name=op.f('fk_employees_access_changed_by_employees'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('max_user_id', name=op.f('uq_employees_max_user_id'))
    )
    op.create_index('ix_employees_role_can_start_trip', 'employees', ['role', 'can_start_trip'], unique=False)
    op.create_table('integration_state',
    sa.Column('integration_key', sa.Text(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('poll_marker', sa.Text(), nullable=True),
    sa.Column('poller_lease_owner', sa.Text(), nullable=True),
    sa.Column('poller_lease_token', sa.Text(), nullable=True),
    sa.Column('poller_lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("mode IN ('webhook', 'polling')", name=op.f('ck_integration_state_mode')),
    sa.CheckConstraint('version > 0', name=op.f('ck_integration_state_version_positive')),
    sa.PrimaryKeyConstraint('integration_key', name=op.f('pk_integration_state'))
    )
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('aggregate_type', sa.Text(), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_version', sa.BigInteger(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expanded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('trip_started', 'trip_completed', 'trip_admin_closed', 'issue_created', 'issue_resolved', 'vehicle_blocked', 'access_changed')", name=op.f('ck_outbox_events_event_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events')),
    sa.UniqueConstraint('event_type', 'aggregate_type', 'aggregate_id', 'aggregate_version', name='uq_outbox_events_aggregate')
    )
    op.create_index('ix_outbox_events_unexpanded', 'outbox_events', ['occurred_at'], unique=False, postgresql_where=sa.text('expanded_at IS NULL'))
    op.create_table('rules_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_label', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_sha256', sa.String(length=64), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(body) BETWEEN 1 AND 10000', name=op.f('ck_rules_versions_body_len')),
    sa.CheckConstraint('char_length(version_label) BETWEEN 1 AND 50', name=op.f('ck_rules_versions_label_len')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rules_versions')),
    sa.UniqueConstraint('version_label', name=op.f('uq_rules_versions_version_label'))
    )
    op.create_index('uq_rules_versions_current', 'rules_versions', ['is_current'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_kind', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("actor_kind IN ('employee', 'admin', 'system')", name=op.f('ck_audit_log_actor_kind')),
    sa.ForeignKeyConstraint(['actor_id'], ['employees.id'], name=op.f('fk_audit_log_actor_id_employees'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_actor', 'audit_log', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id', 'created_at', 'id'], unique=False)
    op.create_table('challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('target_version', sa.BigInteger(), nullable=True),
    sa.Column('intent_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('intent_sha256', sa.String(length=64), nullable=False),
    sa.Column('operand_a', sa.SmallInteger(), nullable=False),
    sa.Column('operand_b', sa.SmallInteger(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_answer', sa.SmallInteger(), nullable=False),
    sa.Column('wrong_attempts', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('solved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(options) = 'array' AND jsonb_array_length(options) = 4", name=op.f('ck_challenges_options')),
    sa.CheckConstraint("purpose IN ('take', 'return', 'vehicle_block', 'vehicle_unblock', 'employee_grant', 'employee_access', 'admin_close')", name=op.f('ck_challenges_purpose')),
    sa.CheckConstraint('operand_a BETWEEN 1 AND 9 AND operand_b BETWEEN 1 AND 9', name=op.f('ck_challenges_operands')),
    sa.CheckConstraint('version > 0', name=op.f('ck_challenges_version_positive')),
    sa.CheckConstraint('wrong_attempts BETWEEN 0 AND 3', name=op.f('ck_challenges_attempts')),
    sa.ForeignKeyConstraint(['actor_id'], ['employees.id'], name=op.f('fk_challenges_actor_id_employees'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenges'))
    )
    op.create_index('ix_challenges_actor_purpose_expires', 'challenges', ['actor_id', 'purpose', 'expires_at'], unique=False)
    op.create_table('conversation_states',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('flow', sa.Text(), nullable=False),
    sa.Column('step', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pending_input_kind', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("pending_input_kind IS NULL OR pending_input_kind IN ('text', 'photo', 'geo', 'none')", name=op.f('ck_conversation_states_pending_kind')),
    sa.CheckConstraint('version > 0', name=op.f('ck_conversation_states_version_positive')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_conversation_states_employee_id_employees'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('employee_id', name=op.f('pk_conversation_states'))
    )
    op.create_table('idempotency_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('request_sha256', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('operation', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resource_type', sa.Text(), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("status IN ('processing', 'completed')", name=op.f('ck_idempotency_records_status')),
    sa.ForeignKeyConstraint(['actor_id'], ['employees.id'], name=op.f('fk_idempotency_records_actor_id_employees'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_records')),
    sa.UniqueConstraint('scope', 'key', name='uq_idempotency_records_scope_key')
    )
    op.create_index('ix_idempotency_records_expires', 'idempotency_records', ['expires_at'], unique=False)
    op.create_table('inbound_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('integration_key', sa.Text(), nullable=False),
    sa.Column('event_key', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_max_user_id', sa.BigInteger(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_schema_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('lease_owner', sa.Text(), nullable=True),
    sa.Column('lease_token', sa.Text(), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error_code', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("event_type IN ('bot_started', 'message_created', 'message_callback')", name=op.f('ck_inbound_events_event_type')),
    sa.CheckConstraint("status IN ('pending', 'processing', 'done', 'retry', 'dead')", name=op.f('ck_inbound_events_status')),
    sa.ForeignKeyConstraint(['actor_id'], ['employees.id'], name=op.f('fk_inbound_events_actor_id_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['integration_key'], ['integration_state.integration_key'], name=op.f('fk_inbound_events_integration_key_integration_state'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbound_events')),
    sa.UniqueConstraint('integration_key', 'event_key', name='uq_inbound_events_key'),
    sa.UniqueConstraint('sequence', name=op.f('uq_inbound_events_sequence'))
    )
    op.create_index('ix_inbound_events_actor', 'inbound_events', ['actor_max_user_id', 'sequence'], unique=False)
    op.create_index('ix_inbound_events_queue', 'inbound_events', ['status', 'next_attempt_at', 'received_at'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Text(), server_default=sa.text("'max'"), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_owner', sa.Text(), nullable=True),
    sa.Column('lease_token', sa.Text(), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.Text(), nullable=True),
    sa.Column('last_error_code', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'sending', 'sent', 'retry', 'dead')", name=op.f('ck_notification_deliveries_status')),
    sa.ForeignKeyConstraint(['event_id'], ['outbox_events.id'], name=op.f('fk_notification_deliveries_event_id_outbox_events'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipient_id'], ['employees.id'], name=op.f('fk_notification_deliveries_recipient_id_employees'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries')),
    sa.UniqueConstraint('event_id', 'recipient_id', 'channel', name='uq_notification_deliveries_target')
    )
    op.create_index('ix_notification_deliveries_queue', 'notification_deliveries', ['status', 'next_attempt_at'], unique=False)
    op.create_table('photo_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('bucket', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('source_event_key', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('scope_type', sa.Text(), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('staging_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("mime_type IN ('image/jpeg', 'image/png', 'image/webp')", name=op.f('ck_photo_assets_mime')),
    sa.CheckConstraint("purpose IN ('inspection', 'issue')", name=op.f('ck_photo_assets_purpose')),
    sa.CheckConstraint("scope_type IN ('inspection', 'trip', 'vehicle')", name=op.f('ck_photo_assets_scope_type')),
    sa.CheckConstraint("sha256 ~ '^[a-f0-9]{64}$'", name=op.f('ck_photo_assets_sha256_hex')),
    sa.CheckConstraint("state IN ('staged', 'ready', 'delete_pending', 'deleted')", name=op.f('ck_photo_assets_state')),
    sa.CheckConstraint('size_bytes > 0 AND size_bytes <= 10485760', name=op.f('ck_photo_assets_size')),
    sa.CheckConstraint('width > 0 AND height > 0 AND width::bigint * height <= 25000000', name=op.f('ck_photo_assets_pixels')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['employees.id'], name=op.f('fk_photo_assets_uploaded_by_employees'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photo_assets')),
    sa.UniqueConstraint('id', 'sha256', name='uq_photo_assets_id_sha256'),
    sa.UniqueConstraint('object_key', name=op.f('uq_photo_assets_object_key'))
    )
    op.create_index('ix_photo_assets_scope', 'photo_assets', ['uploaded_by', 'scope_type', 'scope_id'], unique=False)
    op.create_index('ix_photo_assets_state_staging', 'photo_assets', ['state', 'staging_expires_at'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plate', sa.Text(), nullable=False),
    sa.Column('plate_normalized', sa.Text(), nullable=False),
    sa.Column('make', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('key_instructions', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('manual_blocked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('block_reason', sa.Text(), nullable=True),
    sa.Column('blocked_by', sa.UUID(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('current_parking_location_id', sa.UUID(), nullable=True),
    sa.Column('current_fuel', sa.SmallInteger(), nullable=True),
    sa.Column('fuel_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_odometer_km', sa.BigInteger(), nullable=True),
    sa.Column('odometer_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_inspection_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('NOT manual_blocked OR char_length(block_reason) > 0', name=op.f('ck_vehicles_block_reason')),
    sa.CheckConstraint('char_length(description) <= 1000 AND char_length(key_instructions) <= 1000', name=op.f('ck_vehicles_text_len')),
    sa.CheckConstraint('char_length(plate) BETWEEN 1 AND 20', name=op.f('ck_vehicles_plate_len')),
    sa.CheckConstraint('current_fuel IS NULL OR current_fuel IN (0, 25, 50, 75, 100)', name=op.f('ck_vehicles_fuel')),
    sa.CheckConstraint('current_odometer_km IS NULL OR current_odometer_km >= 0', name=op.f('ck_vehicles_odometer')),
    sa.CheckConstraint('version > 0', name=op.f('ck_vehicles_version_positive')),
    sa.ForeignKeyConstraint(['blocked_by'], ['employees.id'], name=op.f('fk_vehicles_blocked_by_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['current_parking_location_id'], ['parking_locations.id'], name=op.f('fk_vehicles_current_parking_location_id_parking_locations'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['last_inspection_id'], ['inspections.id'], name=op.f('fk_vehicles_last_inspection_id_inspections'), ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles')),
    sa.UniqueConstraint('plate_normalized', name=op.f('uq_vehicles_plate_normalized'))
    )
    op.create_table('checkout_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('step', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('intent_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rules_version_id', sa.UUID(), nullable=True),
    sa.Column('rules_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('no_new_issues', sa.Boolean(), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("status IN ('holding', 'started', 'cancelled', 'expired', 'rejected')", name=op.f('ck_checkout_attempts_status')),
    sa.CheckConstraint('(rules_version_id IS NULL) = (rules_accepted_at IS NULL)', name=op.f('ck_checkout_attempts_rules_pair')),
    sa.CheckConstraint('version > 0', name=op.f('ck_checkout_attempts_version_positive')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_checkout_attempts_employee_id_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rules_version_id'], ['rules_versions.id'], name=op.f('fk_checkout_attempts_rules_version_id_rules_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_checkout_attempts_vehicle_id_vehicles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkout_attempts'))
    )
    op.create_index('ix_checkout_attempts_employee_created', 'checkout_attempts', ['employee_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_checkout_attempts_holding_expires', 'checkout_attempts', ['expires_at'], unique=False, postgresql_where=sa.text("status = 'holding'"))
    op.create_index('ix_checkout_attempts_vehicle_created', 'checkout_attempts', ['vehicle_id', 'created_at', 'id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('checkout_attempt_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.Column('close_reason', sa.Text(), nullable=True),
    sa.Column('missing_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("(status IN ('active', 'returning') AND ended_at IS NULL) OR (status IN ('completed', 'closed_by_admin') AND ended_at IS NOT NULL AND ended_at >= started_at)", name=op.f('ck_trips_ended')),
    sa.CheckConstraint("jsonb_typeof(missing_data) = 'array'", name=op.f('ck_trips_missing_data_array')),
    sa.CheckConstraint("status <> 'closed_by_admin' OR (closed_by IS NOT NULL AND char_length(close_reason) > 0)", name=op.f('ck_trips_admin_close')),
    sa.CheckConstraint("status IN ('active', 'returning', 'completed', 'closed_by_admin')", name=op.f('ck_trips_status')),
    sa.CheckConstraint('version > 0', name=op.f('ck_trips_version_positive')),
    sa.ForeignKeyConstraint(['checkout_attempt_id'], ['checkout_attempts.id'], name=op.f('fk_trips_checkout_attempt_id_checkout_attempts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['closed_by'], ['employees.id'], name=op.f('fk_trips_closed_by_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_trips_employee_id_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_trips_vehicle_id_vehicles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips')),
    sa.UniqueConstraint('checkout_attempt_id', name=op.f('uq_trips_checkout_attempt_id'))
    )
    op.create_index('ix_trips_employee_started', 'trips', ['employee_id', sa.literal_column('started_at DESC'), 'id'], unique=False)
    op.create_index('ix_trips_status_started', 'trips', ['status', sa.literal_column('started_at DESC'), 'id'], unique=False)
    op.create_index('ix_trips_vehicle_started', 'trips', ['vehicle_id', sa.literal_column('started_at DESC'), 'id'], unique=False)
    op.create_index('uq_trips_open_employee', 'trips', ['employee_id'], unique=True, postgresql_where=sa.text("status IN ('active', 'returning')"))
    op.create_index('uq_trips_open_vehicle', 'trips', ['vehicle_id'], unique=True, postgresql_where=sa.text("status IN ('active', 'returning')"))
    op.create_table('return_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('step', sa.Text(), nullable=False),
    sa.Column('intent_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parking_location_id', sa.UUID(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'cancelled', 'completed', 'admin_closed')", name=op.f('ck_return_attempts_status')),
    sa.CheckConstraint('version > 0', name=op.f('ck_return_attempts_version_positive')),
    sa.ForeignKeyConstraint(['parking_location_id'], ['parking_locations.id'], name=op.f('fk_return_attempts_parking_location_id_parking_locations'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_return_attempts_trip_id_trips'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_return_attempts'))
    )
    op.create_index('ix_return_attempts_trip', 'return_attempts', ['trip_id', 'created_at'], unique=False)
    op.create_index('uq_return_attempts_draft', 'return_attempts', ['trip_id'], unique=True, postgresql_where=sa.text("status = 'draft'"))
    op.create_table('vehicle_assignments',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('checkout_attempt_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('phase', sa.Text(), nullable=False),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("(phase = 'hold' AND trip_id IS NULL AND hold_expires_at IS NOT NULL) OR (phase = 'trip' AND trip_id IS NOT NULL AND hold_expires_at IS NULL)", name=op.f('ck_vehicle_assignments_phase')),
    sa.CheckConstraint('version > 0', name=op.f('ck_vehicle_assignments_version_positive')),
    sa.ForeignKeyConstraint(['checkout_attempt_id'], ['checkout_attempts.id'], name=op.f('fk_vehicle_assignments_checkout_attempt_id_checkout_attempts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_vehicle_assignments_employee_id_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_vehicle_assignments_trip_id_trips'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_vehicle_assignments_vehicle_id_vehicles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('vehicle_id', name=op.f('pk_vehicle_assignments')),
    sa.UniqueConstraint('checkout_attempt_id', name=op.f('uq_vehicle_assignments_checkout_attempt_id')),
    sa.UniqueConstraint('employee_id', name=op.f('uq_vehicle_assignments_employee_id')),
    sa.UniqueConstraint('trip_id', name=op.f('uq_vehicle_assignments_trip_id'))
    )
    op.create_table('inspections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phase', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('checkout_attempt_id', sa.UUID(), nullable=True),
    sa.Column('return_attempt_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('fuel_level', sa.SmallInteger(), nullable=True),
    sa.Column('odometer_km', sa.BigInteger(), nullable=True),
    sa.Column('new_damage', sa.Boolean(), nullable=True),
    sa.Column('cabin_clean', sa.Boolean(), nullable=True),
    sa.Column('parking_allowed', sa.Boolean(), nullable=True),
    sa.Column('keys_returned', sa.Boolean(), nullable=True),
    sa.Column('car_locked', sa.Boolean(), nullable=True),
    sa.Column('photos_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("(phase = 'before' AND checkout_attempt_id IS NOT NULL AND return_attempt_id IS NULL) OR (phase = 'after' AND return_attempt_id IS NOT NULL AND checkout_attempt_id IS NULL)", name=op.f('ck_inspections_owner')),
    sa.CheckConstraint("phase IN ('before', 'after')", name=op.f('ck_inspections_phase')),
    sa.CheckConstraint("status <> 'finalized' OR (fuel_level IS NOT NULL AND odometer_km IS NOT NULL AND photos_confirmed_at IS NOT NULL AND finalized_at IS NOT NULL)", name=op.f('ck_inspections_finalized_complete')),
    sa.CheckConstraint("status <> 'finalized' OR phase <> 'after' OR (new_damage IS NOT NULL AND cabin_clean IS NOT NULL AND parking_allowed IS NOT NULL AND keys_returned IS NOT NULL AND car_locked IS NOT NULL)", name=op.f('ck_inspections_after_answers')),
    sa.CheckConstraint("status IN ('draft', 'finalized', 'abandoned')", name=op.f('ck_inspections_status')),
    sa.CheckConstraint('fuel_level IS NULL OR fuel_level IN (0, 25, 50, 75, 100)', name=op.f('ck_inspections_fuel')),
    sa.CheckConstraint('odometer_km IS NULL OR odometer_km >= 0', name=op.f('ck_inspections_odometer')),
    sa.CheckConstraint('version > 0', name=op.f('ck_inspections_version_positive')),
    sa.ForeignKeyConstraint(['author_id'], ['employees.id'], name=op.f('fk_inspections_author_id_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['checkout_attempt_id'], ['checkout_attempts.id'], name=op.f('fk_inspections_checkout_attempt_id_checkout_attempts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_attempt_id'], ['return_attempts.id'], name=op.f('fk_inspections_return_attempt_id_return_attempts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspections')),
    sa.UniqueConstraint('checkout_attempt_id', name=op.f('uq_inspections_checkout_attempt_id')),
    sa.UniqueConstraint('return_attempt_id', name=op.f('uq_inspections_return_attempt_id'))
    )
    op.create_table('parking_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('return_attempt_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('landmark', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source = 'seed' OR author_id IS NOT NULL", name=op.f('ck_parking_locations_author')),
    sa.CheckConstraint("source IN ('max_geo', 'manual_map', 'admin', 'seed')", name=op.f('ck_parking_locations_source')),
    sa.CheckConstraint("source NOT IN ('admin', 'seed') OR return_attempt_id IS NULL", name=op.f('ck_parking_locations_admin_no_return')),
    sa.CheckConstraint('landmark IS NULL OR char_length(landmark) <= 500', name=op.f('ck_parking_locations_landmark_len')),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name=op.f('ck_parking_locations_latitude')),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name=op.f('ck_parking_locations_longitude')),
    sa.ForeignKeyConstraint(['author_id'], ['employees.id'], name=op.f('fk_parking_locations_author_id_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_attempt_id'], ['return_attempts.id'], name=op.f('fk_parking_locations_return_attempt_id_return_attempts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_parking_locations_vehicle_id_vehicles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parking_locations'))
    )
    op.create_index('ix_parking_locations_vehicle_confirmed', 'parking_locations', ['vehicle_id', sa.literal_column('confirmed_at DESC')], unique=False)
    op.create_table('inspection_photos',
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('slot', sa.SmallInteger(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('attached_by', sa.UUID(), nullable=False),
    sa.Column('attached_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_event_key', sa.Text(), nullable=False),
    sa.CheckConstraint('slot BETWEEN 1 AND 8', name=op.f('ck_inspection_photos_slot')),
    sa.ForeignKeyConstraint(['asset_id', 'content_sha256'], ['photo_assets.id', 'photo_assets.sha256'], name='fk_inspection_photos_asset', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['attached_by'], ['employees.id'], name=op.f('fk_inspection_photos_attached_by_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], name=op.f('fk_inspection_photos_inspection_id_inspections'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('inspection_id', 'slot', name=op.f('pk_inspection_photos')),
    sa.UniqueConstraint('asset_id', name=op.f('uq_inspection_photos_asset_id')),
    sa.UniqueConstraint('inspection_id', 'content_sha256', name='uq_inspection_photos_sha'),
    sa.UniqueConstraint('inspection_id', 'source_event_key', name='uq_inspection_photos_event')
    )
    op.create_table('issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('inspection_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'open'"), nullable=False),
    sa.Column('blocks_issuance', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('resolution_comment', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("(status IN ('open', 'in_progress') AND blocks_issuance) OR (status IN ('resolved', 'known_nonblocking') AND NOT blocks_issuance AND resolved_by IS NOT NULL AND resolved_at IS NOT NULL AND char_length(resolution_comment) > 0)", name=op.f('ck_issues_resolution')),
    sa.CheckConstraint("category IN ('body_damage', 'mechanical', 'cleanliness', 'keys', 'other')", name=op.f('ck_issues_category')),
    sa.CheckConstraint("stage IN ('before', 'during', 'return', 'after')", name=op.f('ck_issues_stage')),
    sa.CheckConstraint("status IN ('open', 'in_progress', 'resolved', 'known_nonblocking')", name=op.f('ck_issues_status')),
    sa.CheckConstraint('char_length(description) BETWEEN 1 AND 1000', name=op.f('ck_issues_description_len')),
    sa.CheckConstraint('version > 0', name=op.f('ck_issues_version_positive')),
    sa.ForeignKeyConstraint(['author_id'], ['employees.id'], name=op.f('fk_issues_author_id_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], name=op.f('fk_issues_inspection_id_inspections'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by'], ['employees.id'], name=op.f('fk_issues_resolved_by_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_issues_trip_id_trips'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_issues_vehicle_id_vehicles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issues'))
    )
    op.create_index('ix_issues_status_created', 'issues', ['status', 'created_at'], unique=False)
    op.create_index('ix_issues_trip', 'issues', ['trip_id'], unique=False)
    op.create_index('ix_issues_updated', 'issues', [sa.literal_column('updated_at DESC'), 'id'], unique=False)
    op.create_index('ix_issues_vehicle_status_created', 'issues', ['vehicle_id', 'status', 'created_at'], unique=False)
    op.create_table('issue_photos',
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('attached_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('ordinal BETWEEN 1 AND 3', name=op.f('ck_issue_photos_ordinal')),
    sa.ForeignKeyConstraint(['asset_id'], ['photo_assets.id'], name=op.f('fk_issue_photos_asset_id_photo_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name=op.f('fk_issue_photos_issue_id_issues'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('issue_id', 'ordinal', name=op.f('pk_issue_photos')),
    sa.UniqueConstraint('asset_id', name=op.f('uq_issue_photos_asset_id'))
    )
    # Отложенные циклические FK (DATABASE §7 шаг 5).
    op.create_foreign_key('fk_vehicles_current_parking_location_id_parking_locations', 'vehicles',
                          'parking_locations', ['current_parking_location_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_vehicles_last_inspection_id_inspections', 'vehicles',
                          'inspections', ['last_inspection_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_return_attempts_parking_location_id_parking_locations', 'return_attempts',
                          'parking_locations', ['parking_location_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_return_attempts_parking_location_id_parking_locations', 'return_attempts',
                       type_='foreignkey')
    op.drop_constraint('fk_vehicles_last_inspection_id_inspections', 'vehicles', type_='foreignkey')
    op.drop_constraint('fk_vehicles_current_parking_location_id_parking_locations', 'vehicles',
                       type_='foreignkey')
    op.drop_table('issue_photos')
    op.drop_index('ix_issues_vehicle_status_created', table_name='issues')
    op.drop_index('ix_issues_updated', table_name='issues')
    op.drop_index('ix_issues_trip', table_name='issues')
    op.drop_index('ix_issues_status_created', table_name='issues')
    op.drop_table('issues')
    op.drop_table('inspection_photos')
    op.drop_index('ix_parking_locations_vehicle_confirmed', table_name='parking_locations')
    op.drop_table('parking_locations')
    op.drop_table('inspections')
    op.drop_table('vehicle_assignments')
    op.drop_index('uq_return_attempts_draft', table_name='return_attempts', postgresql_where=sa.text("status = 'draft'"))
    op.drop_index('ix_return_attempts_trip', table_name='return_attempts')
    op.drop_table('return_attempts')
    op.drop_index('uq_trips_open_vehicle', table_name='trips', postgresql_where=sa.text("status IN ('active', 'returning')"))
    op.drop_index('uq_trips_open_employee', table_name='trips', postgresql_where=sa.text("status IN ('active', 'returning')"))
    op.drop_index('ix_trips_vehicle_started', table_name='trips')
    op.drop_index('ix_trips_status_started', table_name='trips')
    op.drop_index('ix_trips_employee_started', table_name='trips')
    op.drop_table('trips')
    op.drop_index('ix_checkout_attempts_vehicle_created', table_name='checkout_attempts')
    op.drop_index('ix_checkout_attempts_holding_expires', table_name='checkout_attempts', postgresql_where=sa.text("status = 'holding'"))
    op.drop_index('ix_checkout_attempts_employee_created', table_name='checkout_attempts')
    op.drop_table('checkout_attempts')
    op.drop_table('vehicles')
    op.drop_index('ix_photo_assets_state_staging', table_name='photo_assets')
    op.drop_index('ix_photo_assets_scope', table_name='photo_assets')
    op.drop_table('photo_assets')
    op.drop_index('ix_notification_deliveries_queue', table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index('ix_inbound_events_queue', table_name='inbound_events')
    op.drop_index('ix_inbound_events_actor', table_name='inbound_events')
    op.drop_table('inbound_events')
    op.drop_index('ix_idempotency_records_expires', table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_table('conversation_states')
    op.drop_index('ix_challenges_actor_purpose_expires', table_name='challenges')
    op.drop_table('challenges')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_index('ix_audit_log_actor', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('uq_rules_versions_current', table_name='rules_versions', postgresql_where=sa.text('is_current'))
    op.drop_table('rules_versions')
    op.drop_index('ix_outbox_events_unexpanded', table_name='outbox_events', postgresql_where=sa.text('expanded_at IS NULL'))
    op.drop_table('outbox_events')
    op.drop_table('integration_state')
    op.drop_index('ix_employees_role_can_start_trip', table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
